import type { Recordable } from '@vben/types';
import { requestClient } from '#/api/request';
const baseUrl='/api/v1/mes/quality';
export interface Inspection{id:number;inspection_no:string;inspection_type:string;material_id:number;lot_id?:number;sample_quantity:number;accepted_quantity:number;rejected_quantity:number;status:string;result?:string;conclusion?:string;created_time:string;}
export interface Ncr{id:number;ncr_no:string;inspection_id:number;material_id:number;lot_id?:number;nonconforming_quantity:number;defect_description:string;severity:string;status:string;sla_due_at?:string;sla_owner_id?:number;created_time:string;}
export interface Disposition{id:number;disposition_no:string;ncr_id:number;disposition_type:string;quantity:number;status:string;warehouse_id?:number;location_id?:number;stock_transaction_id?:number;reinspection_id?:number;decision_reason?:string;}
export interface InspectionItem{id:number;item_code:string;item_name:string;value_type:'BOOLEAN'|'NUMERIC'|'TEXT';unit_label?:string;status:'ACTIVE'|'INACTIVE';}
export interface SamplingPlan{id:number;plan_code:string;plan_name:string;sample_size:number;acceptance_number:number;status:'ACTIVE'|'INACTIVE';}
export interface InspectionTemplate{id:number;template_code:string;template_name:string;material_id:number;template_version:string;inspection_type:string;sampling_plan_id?:number;status:'ACTIVE'|'DRAFT'|'INACTIVE';remark?:string;}
export interface InspectionStandard{id:number;template_id:number;line_no:number;inspection_item_id:number;lower_limit?:number;upper_limit?:number;expected_boolean?:boolean;expected_text?:string;required:boolean;remark?:string;}
export interface InspectionResultLine{id:number;inspection_id:number;template_id:number;standard_id:number;inspection_item_id:number;line_no_snapshot:number;item_code_snapshot:string;item_name_snapshot:string;value_type_snapshot:string;is_qualified:boolean;numeric_value?:number;boolean_value?:boolean;text_value?:string;}
export interface ReworkOrder{id:number;rework_no:string;ncr_id:number;material_id:number;lot_id:number;quantity:number;production_work_order_id?:number;status:'PLANNED'|'IN_PROGRESS'|'AWAITING_RETEST'|'RELEASED'|'CANCELLED';reinspection_id?:number;started_at?:string;completed_at?:string;released_at?:string;remark?:string;created_time:string;}
export interface Capa{id:number;capa_no:string;ncr_id:number;status:'OPEN'|'ANALYSIS'|'ACTION'|'VERIFYING'|'CLOSED'|'CANCELLED';d1_team_summary?:string;d2_problem_description?:string;d3_containment_summary?:string;d4_root_cause?:string;d5_corrective_plan?:string;d6_implementation_summary?:string;d7_prevention_summary?:string;d8_closure_summary?:string;owner_id?:number;due_at?:string;closed_at?:string;created_time:string;}
export interface CapaAction{id:number;action_no:string;capa_id:number;action_type:'CONTAINMENT'|'CORRECTIVE'|'PREVENTIVE';description:string;owner_id?:number;due_at?:string;status:'OPEN'|'IN_PROGRESS'|'COMPLETED'|'VERIFIED'|'CANCELLED';evidence?:string;completed_at?:string;verified_at?:string;created_time:string;}
export interface CapaVerification{id:number;capa_id:number;result:'PASS'|'FAIL';notes?:string;verified_by?:number;verified_at:string;}
export interface CustomerComplaint{id:number;complaint_no:string;customer_id:number;customer_code_snapshot:string;customer_name_snapshot:string;shipment_id?:number;material_id?:number;lot_id?:number;quantity?:number;title:string;description:string;status:string;rma_id?:number;ncr_id?:number;capa_id?:number;resolution_type?:string;resolution_notes?:string;closed_at?:string;sla_due_at?:string;sla_owner_id?:number;created_time:string;}
export interface CustomerReturnLine{id:number;line_no:number;shipment_line_id?:number;material_id:number;lot_id?:number;warehouse_id:number;location_id:number;quantity:number;stock_transaction_id?:number;inspection_id?:number;}
export interface CustomerReturn{id:number;return_no:string;complaint_id:number;customer_id:number;shipment_id?:number;status:string;ncr_id?:number;resolution_type?:string;resolution_notes?:string;received_at?:string;inspected_at?:string;closed_at?:string;sla_due_at?:string;sla_owner_id?:number;created_time:string;lines:CustomerReturnLine[];}
export interface AfterSalesOrder{id:number;execution_no:string;return_id:number;complaint_id:number;customer_id:number;resolution_type:string;material_id:number;quantity:number;warehouse_id:number;location_id:number;lot_id?:number;replacement_material_id?:number;replacement_lot_id?:number;replacement_quantity?:number;status:string;stock_transaction_id?:number;execution_notes?:string;completed_at?:string;sla_due_at?:string;sla_owner_id?:number;created_time:string;}
export interface AfterSalesRepairTask{id:number;task_no:string;after_sales_order_id:number;status:string;description:string;result_notes?:string;started_at?:string;completed_at?:string;}
export interface OperationDashboardSummary{status_counts:Record<string,Record<string,number>>;overdue_counts:Record<string,number>;average_close_hours:Record<string,number>;repeated_defects:Array<{key:string;count:number}>;inventory_impact:{transaction_count:number;quantity_delta:number;absolute_quantity:number};open_alerts:number;owner_todo_count:number;}
export interface SlaAlert{id:number;alert_no:string;entity_type:string;entity_id:number;rule_id:number;title:string;due_at:string;status:string;owner_id?:number;warning_at?:string;escalated_at?:string;escalation_level:number;acknowledged_at?:string;resolved_at?:string;}
export const getInspectionsApi=(params?:Recordable<any>)=>requestClient.get<Inspection[]>(`${baseUrl}/inspections`,{params});
export const createInspectionApi=(data:Recordable<any>)=>requestClient.post<Inspection>(`${baseUrl}/inspections`,data);
export const completeInspectionApi=(id:number,data:Recordable<any>)=>requestClient.post<Inspection>(`${baseUrl}/inspections/${id}/complete`,data);
export const getNcrsApi=(params?:Recordable<any>)=>requestClient.get<Ncr[]>(`${baseUrl}/ncrs`,{params});
export const createNcrApi=(data:Recordable<any>)=>requestClient.post<Ncr>(`${baseUrl}/ncrs`,data);
export const getDispositionsApi=(id:number)=>requestClient.get<Disposition[]>(`${baseUrl}/ncrs/${id}/dispositions`);
export const createDispositionApi=(data:Recordable<any>)=>requestClient.post<Disposition>(`${baseUrl}/dispositions`,data);
export const executeDispositionApi=(id:number)=>requestClient.post<Disposition>(`${baseUrl}/dispositions/${id}/execute`);
export const closeNcrApi=(id:number,root_cause?:string)=>requestClient.post<Ncr>(`${baseUrl}/ncrs/${id}/close`,{root_cause});
export const getInspectionItemsApi=()=>requestClient.get<InspectionItem[]>(`${baseUrl}/inspection-items`);
export const createInspectionItemApi=(data:Recordable<any>)=>requestClient.post<InspectionItem>(`${baseUrl}/inspection-items`,data);
export const setInspectionItemStatusApi=(id:number,status:'ACTIVE'|'INACTIVE')=>requestClient.put<InspectionItem>(`${baseUrl}/inspection-items/${id}/status`,{status});
export const getSamplingPlansApi=()=>requestClient.get<SamplingPlan[]>(`${baseUrl}/sampling-plans`);
export const createSamplingPlanApi=(data:Recordable<any>)=>requestClient.post<SamplingPlan>(`${baseUrl}/sampling-plans`,data);
export const setSamplingPlanStatusApi=(id:number,status:'ACTIVE'|'INACTIVE')=>requestClient.put<SamplingPlan>(`${baseUrl}/sampling-plans/${id}/status`,{status});
export const getInspectionTemplatesApi=()=>requestClient.get<InspectionTemplate[]>(`${baseUrl}/inspection-templates`);
export const createInspectionTemplateApi=(data:Recordable<any>)=>requestClient.post<InspectionTemplate>(`${baseUrl}/inspection-templates`,data);
export const getInspectionStandardsApi=(id:number)=>requestClient.get<InspectionStandard[]>(`${baseUrl}/inspection-templates/${id}/standards`);
export const createInspectionStandardApi=(id:number,data:Recordable<any>)=>requestClient.post<InspectionStandard>(`${baseUrl}/inspection-templates/${id}/standards`,data);
export const activateInspectionTemplateApi=(id:number)=>requestClient.post<InspectionTemplate>(`${baseUrl}/inspection-templates/${id}/activate`);
export const deactivateInspectionTemplateApi=(id:number)=>requestClient.post<InspectionTemplate>(`${baseUrl}/inspection-templates/${id}/deactivate`);
export const getInspectionResultsApi=(id:number)=>requestClient.get<InspectionResultLine[]>(`${baseUrl}/inspections/${id}/results`);
export const submitInspectionResultsApi=(id:number,data:Recordable<any>)=>requestClient.post<InspectionResultLine[]>(`${baseUrl}/inspections/${id}/results`,data);
export const getReworkOrdersApi=(params?:Recordable<any>)=>requestClient.get<ReworkOrder[]>(`${baseUrl}/rework-orders`,{params});
export const createReworkWorkOrderApi=(id:number)=>requestClient.post<ReworkOrder>(`${baseUrl}/rework-orders/${id}/create-work-order`);
export const startReworkApi=(id:number)=>requestClient.post<ReworkOrder>(`${baseUrl}/rework-orders/${id}/start`);
export const completeReworkApi=(id:number)=>requestClient.post<ReworkOrder>(`${baseUrl}/rework-orders/${id}/complete`);
export const getCapasApi=(params?:Recordable<any>)=>requestClient.get<Capa[]>(`${baseUrl}/capas`,{params});
export const createCapaApi=(data:Recordable<any>)=>requestClient.post<Capa>(`${baseUrl}/capas`,data);
export const updateCapaApi=(id:number,data:Recordable<any>)=>requestClient.put<Capa>(`${baseUrl}/capas/${id}`,data);
export const getCapaActionsApi=(id:number)=>requestClient.get<CapaAction[]>(`${baseUrl}/capas/${id}/actions`);
export const createCapaActionApi=(id:number,data:Recordable<any>)=>requestClient.post<CapaAction>(`${baseUrl}/capas/${id}/actions`,data);
export const setCapaActionStatusApi=(capaId:number,actionId:number,data:Recordable<any>)=>requestClient.post<CapaAction>(`${baseUrl}/capas/${capaId}/actions/${actionId}/status`,data);
export const getCapaVerificationsApi=(id:number)=>requestClient.get<CapaVerification[]>(`${baseUrl}/capas/${id}/verifications`);
export const verifyCapaApi=(id:number,data:Recordable<any>)=>requestClient.post<CapaVerification>(`${baseUrl}/capas/${id}/verify`,data);
export const closeCapaApi=(id:number)=>requestClient.post<Capa>(`${baseUrl}/capas/${id}/close`);
export const getCustomerComplaintsApi=(params?:Recordable<any>)=>requestClient.get<CustomerComplaint[]>(`${baseUrl}/customer-complaints`,{params});
export const createCustomerComplaintApi=(data:Recordable<any>)=>requestClient.post<CustomerComplaint>(`${baseUrl}/customer-complaints`,data);
export const getCustomerReturnsApi=(params?:Recordable<any>)=>requestClient.get<CustomerReturn[]>(`${baseUrl}/customer-returns`,{params});
export const createCustomerReturnApi=(data:Recordable<any>)=>requestClient.post<CustomerReturn>(`${baseUrl}/customer-returns`,data);
export const receiveCustomerReturnApi=(id:number)=>requestClient.post<CustomerReturn>(`${baseUrl}/customer-returns/${id}/receive`);
export const inspectCustomerReturnApi=(id:number,data:Recordable<any>)=>requestClient.post<CustomerReturn>(`${baseUrl}/customer-returns/${id}/inspect`,data);
export const resolveCustomerReturnApi=(id:number,data:Recordable<any>)=>requestClient.post<CustomerReturn>(`${baseUrl}/customer-returns/${id}/resolve`,data);
export const closeCustomerReturnApi=(id:number)=>requestClient.post<CustomerReturn>(`${baseUrl}/customer-returns/${id}/close`);
export const getAfterSalesOrdersApi=(params?:Recordable<any>)=>requestClient.get<AfterSalesOrder[]>(`${baseUrl}/after-sales-orders`,{params});
export const createAfterSalesOrderApi=(returnId:number,data:Recordable<any>)=>requestClient.post<AfterSalesOrder>(`${baseUrl}/customer-returns/${returnId}/after-sales-orders`,data);
export const approveAfterSalesOrderApi=(id:number)=>requestClient.post<AfterSalesOrder>(`${baseUrl}/after-sales-orders/${id}/approve`);
export const startAfterSalesOrderApi=(id:number)=>requestClient.post<AfterSalesOrder>(`${baseUrl}/after-sales-orders/${id}/start`);
export const completeAfterSalesOrderApi=(id:number)=>requestClient.post<AfterSalesOrder>(`${baseUrl}/after-sales-orders/${id}/complete`);
export const cancelAfterSalesOrderApi=(id:number)=>requestClient.post<AfterSalesOrder>(`${baseUrl}/after-sales-orders/${id}/cancel`);
export const getAfterSalesRepairTaskApi=(id:number)=>requestClient.get<AfterSalesRepairTask>(`${baseUrl}/after-sales-orders/${id}/repair-task`);
export const completeAfterSalesRepairTaskApi=(id:number,data:Recordable<any>)=>requestClient.post<AfterSalesRepairTask>(`${baseUrl}/after-sales-orders/${id}/repair-task/complete`,data);
export const getOperationDashboardApi=()=>requestClient.get<OperationDashboardSummary>(`${baseUrl}/operation-dashboard`);
export const getSlaAlertsApi=(params?:Recordable<any>)=>requestClient.get<SlaAlert[]>(`${baseUrl}/sla-alerts`,{params});
export const acknowledgeSlaAlertApi=(id:number)=>requestClient.post<SlaAlert>(`${baseUrl}/sla-alerts/${id}/acknowledge`);
export const escalateSlaAlertApi=(id:number,level=1)=>requestClient.post<SlaAlert>(`${baseUrl}/sla-alerts/${id}/escalate`,{level});
export const closeSlaAlertApi=(id:number)=>requestClient.post<SlaAlert>(`${baseUrl}/sla-alerts/${id}/close`);
