set @scheduling_menu_id = (select id from sys_menu where name = 'MesScheduling' limit 1);
delete from sys_role_menu where menu_id in (select id from sys_menu where parent_id = @scheduling_menu_id) or menu_id = @scheduling_menu_id;
delete from sys_menu where parent_id = @scheduling_menu_id;
delete from sys_menu where id = @scheduling_menu_id;
set @shopfloor_menu_id = (select id from sys_menu where name = 'MesShopfloor' limit 1);
delete from sys_role_menu where menu_id in (select id from sys_menu where parent_id = @shopfloor_menu_id) or menu_id = @shopfloor_menu_id;
delete from sys_menu where parent_id = @shopfloor_menu_id;
delete from sys_menu where id = @shopfloor_menu_id;
drop table if exists mes_aps_dispatch;
drop table if exists mes_workstation_session;
drop table if exists mes_workstation;
drop table if exists mes_production_team_member;
drop table if exists mes_production_team;
drop table if exists mes_aps_operation_schedule;
drop table if exists mes_aps_schedule;
drop table if exists mes_aps_work_center_calendar;
drop table if exists mes_aps_calendar_day;
drop table if exists mes_aps_calendar;
drop table if exists mes_aps_shift;
