from enum import StrEnum
class SalesOrderStatus(StrEnum):
    DRAFT='DRAFT'; CONFIRMED='CONFIRMED'; PARTIALLY_SHIPPED='PARTIALLY_SHIPPED'; SHIPPED='SHIPPED'; CANCELLED='CANCELLED'
class ShipmentStatus(StrEnum):
    POSTED='POSTED'; DELIVERED='DELIVERED'

class DeliveryPerformanceStatus(StrEnum):
    OPEN='OPEN'; IN_TRANSIT='IN_TRANSIT'; OTIF='OTIF'; LATE='LATE'; NOT_IN_FULL='NOT_IN_FULL'; LATE_AND_NOT_IN_FULL='LATE_AND_NOT_IN_FULL'

class DeliveryDelayReason(StrEnum):
    SHORTAGE='SHORTAGE'; CAPACITY_RISK='CAPACITY_RISK'; EXECUTION='EXECUTION'; QUALITY='QUALITY'; LOGISTICS='LOGISTICS'; OTHER='OTHER'
