<script setup lang="ts">
import { computed, h, onMounted, onUnmounted, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { Card, Col, Input, InputNumber, Row, Select, Space, Statistic, Table, Tag, message } from 'antdv-next';
import { approveBudgetApi, approveFixedAssetCountLineApi, autoApInvoiceApi, autoArInvoiceApi, autoReconcileBankStatementApi, calculateInventoryValuationApi, closeFinancePeriodApi, createFixedAssetCountApi, createFixedAssetFromReceiptApi, getBankStatementsApi, getBudgetAlertsApi, getBudgetsApi, getFinanceDashboardApi, getFinancePeriodsApi, getFixedAssetCountApi, getFixedAssetsApi, getPaymentPlansApi, postFixedAssetCountApi, rebuildCashFlowForecastApi, runClosingCheckApi, runFixedAssetDualDepreciationApi, scanFixedAssetCountApi, syncTaxInvoicesApi, type BankStatement, type Budget, type BudgetAlert, type CashFlowForecast, type FinanceDashboard, type FinancePeriod, type FixedAsset, type FixedAssetCount, type FixedAssetCountLine, type InventoryValuation, type PaymentPlan } from '../api';

const periods=ref<FinancePeriod[]>([]); const periodId=ref<number>(); const dashboard=ref<FinanceDashboard>(); const valuation=ref<InventoryValuation[]>([]); const plans=ref<PaymentPlan[]>([]); const statements=ref<BankStatement[]>([]); const budgets=ref<Budget[]>([]); const alerts=ref<BudgetAlert[]>([]); const assets=ref<FixedAsset[]>([]); const forecast=ref<CashFlowForecast>(); const shipmentId=ref<number>(); const receiptId=ref<number>(); const loading=ref(false);
const countTaskId=ref<number>(); const countTask=ref<FixedAssetCount>(); const scanCode=ref(''); const observedCostCenterId=ref<number>(); const countZoneCode=ref(''); const countAssignedUserId=ref<number>(); const evidencePhoto=ref(''); const scanLoading=ref(false); const lastScan=ref<FixedAsset>(); const offlinePending=ref(0); const syncingOffline=ref(false); const online=ref(true);
const offlineStorageKey='erp:finance:fixed-asset-count:offline-v1';
type OfflineScan={taskId:number; data:Record<string,any>; queuedAt:number};
const fmt=(v:unknown)=>Number(v??0).toLocaleString('zh-CN',{maximumFractionDigits:2});
const options=computed(()=>periods.value.map(p=>({label:`${p.period_code} · ${p.status}`,value:p.id})));
async function refresh(){ loading.value=true; try{ dashboard.value=await getFinanceDashboardApi(periodId.value); }finally{loading.value=false;} }
async function calculate(){ if(!periodId.value) return message.warning('请先选择财务期间'); valuation.value=await calculateInventoryValuationApi(periodId.value); message.success(`已完成 ${valuation.value.length} 个物料计价`); await refresh(); }
async function reconcile(statementId:number){ await autoReconcileBankStatementApi(statementId); statements.value=await getBankStatementsApi(); message.success('银行流水自动对账完成'); }
async function autoInvoice(kind:'AR'|'AP'){ const id=kind==='AR'?shipmentId.value:receiptId.value; if(!id) return message.warning(`请输入${kind==='AR'?'发货单':'收货单'} ID`); const today=new Date().toISOString().slice(0,10); const due=new Date(Date.now()+30*86400000).toISOString().slice(0,10); if(kind==='AR') await autoArInvoiceApi(id,{invoice_date:today,due_date:due,tax_rate:0}); else await autoApInvoiceApi(id,{invoice_date:today,due_date:due,tax_rate:0}); plans.value=await getPaymentPlansApi(); message.success('自动开票完成'); }
async function closePeriod(){ if(!periodId.value) return; const checks=await runClosingCheckApi(periodId.value); const blocked=checks.filter((item)=>item.blocking&&item.status==='BLOCK'); if(blocked.length) return message.error(`关账阻断：${blocked.map((item)=>item.check_name).join('、')}`); await closeFinancePeriodApi(periodId.value); message.success('财务期间已关账'); periods.value=await getFinancePeriodsApi(); }
async function syncTax(){ if(!periodId.value) return; await syncTaxInvoicesApi(periodId.value); message.success('税务发票台账已同步'); }
async function rebuildCash(){ if(!periodId.value) return; forecast.value=await rebuildCashFlowForecastApi(periodId.value); message.success('现金流预测已重建'); }
async function approveBudget(id:number){ await approveBudgetApi(id); if(periodId.value) budgets.value=await getBudgetsApi(periodId.value); message.success('预算已审批'); }
async function runDepreciation(){ if(!periodId.value) return; const result:any=await runFixedAssetDualDepreciationApi(periodId.value); assets.value=await getFixedAssetsApi(); message.success(`已完成 ${result?.asset_count||0} 项财税双账折旧`); }
async function assetFromReceipt(){ if(!periodId.value||!receiptId.value) return message.warning('请输入收货单 ID'); const today=new Date().toISOString().slice(0,10); await createFixedAssetFromReceiptApi(receiptId.value,{period_id:periodId.value,invoice_date:today,due_date:today,tax_rate:0,asset_name:`收货资产-${receiptId.value}`,useful_life_months:60,residual_rate:5}); assets.value=await getFixedAssetsApi(); message.success('收货单已匹配发票并生成固定资产'); }
function readOfflineQueue():OfflineScan[]{ try{return JSON.parse(localStorage.getItem(offlineStorageKey)||'[]') as OfflineScan[]}catch{return []} }
function updateOfflinePending(){ offlinePending.value=typeof window==='undefined'?0:readOfflineQueue().length; }
function queueOfflineScan(item:OfflineScan){ const queue=readOfflineQueue(); queue.push(item); localStorage.setItem(offlineStorageKey,JSON.stringify(queue)); updateOfflinePending(); }
function captureEvidence(event:Event){ const file=(event.target as HTMLInputElement).files?.[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ evidencePhoto.value=String(reader.result||''); message.success('照片已暂存在本次扫码证据中'); }; reader.readAsDataURL(file); }
function applyOfflineScan(data:Record<string,any>){ if(!countTask.value) return; const asset=assets.value.find((item)=>item.barcode===data.code||item.serial_number===data.code); if(!asset) return; lastScan.value=asset; const variance=data.observed_cost_center_id&&asset.cost_center_id!==data.observed_cost_center_id?'LOCATION_MISMATCH':'NONE'; const existing=countTask.value.lines.find((line)=>line.asset_id===asset.id); if(existing){ Object.assign(existing,{counted:data.counted!==false,observed_cost_center_id:data.observed_cost_center_id,variance_type:variance,evidence_photo:data.evidence_photo,evidence_note:data.evidence_note,approval_status:'PENDING'}); }else{ countTask.value.lines.push({id:-Date.now(),task_id:countTask.value.id,asset_id:asset.id,barcode_snapshot:asset.barcode,serial_snapshot:asset.serial_number,counted:data.counted!==false,observed_cost_center_id:data.observed_cost_center_id,variance_type:variance,remark:data.remark,evidence_photo:data.evidence_photo,evidence_note:data.evidence_note,approval_status:'PENDING'} as FixedAssetCountLine); } }
async function syncOfflineScans(){ if(syncingOffline.value||typeof navigator==='undefined'||!navigator.onLine) return; const queue=readOfflineQueue(); if(!queue.length) return; syncingOffline.value=true; const remain:OfflineScan[]=[]; let synced=0; for(const item of queue){ try{ await scanFixedAssetCountApi(item.taskId,item.data as any); synced++; if(countTaskId.value===item.taskId) countTask.value=await getFixedAssetCountApi(item.taskId); }catch{ remain.push(item); } } localStorage.setItem(offlineStorageKey,JSON.stringify(remain)); updateOfflinePending(); syncingOffline.value=false; if(synced) message.success(`已自动同步 ${synced} 条离线扫码记录`); }
async function createCountTask(){ if(!periodId.value) return message.warning('请先选择财务期间'); if(!assets.value.length) return message.warning('当前没有可盘点的固定资产'); const created:any=await createFixedAssetCountApi({period_id:periodId.value,zone_code:countZoneCode.value||undefined,assigned_user_id:countAssignedUserId.value,remark:'移动扫码盘点',lines:assets.value.map((asset)=>({asset_id:asset.id}))}); countTaskId.value=created.id; countTask.value=created; message.success(`已创建盘点任务 ${created.task_no}`); }
async function loadCountTask(){ if(!countTaskId.value) return message.warning('请输入盘点任务 ID'); countTask.value=await getFixedAssetCountApi(countTaskId.value); message.success(`已加载 ${countTask.value.task_no}，共 ${countTask.value.lines.length} 项`); }
async function scanCount(){ if(!countTaskId.value) return message.warning('请输入盘点任务 ID'); if(!scanCode.value.trim()) return message.warning('请扫描条码或序列号'); const data={code:scanCode.value.trim(),observed_cost_center_id:observedCostCenterId.value,evidence_photo:evidencePhoto.value||undefined}; if(typeof navigator!=='undefined'&&!navigator.onLine){ queueOfflineScan({taskId:countTaskId.value,data,queuedAt:Date.now()}); applyOfflineScan(data); scanCode.value=''; evidencePhoto.value=''; return message.info('当前离线，扫码记录已缓存，联网后自动同步'); } scanLoading.value=true; try{ const result=await scanFixedAssetCountApi(countTaskId.value,data); lastScan.value=result.asset; countTask.value=await getFixedAssetCountApi(countTaskId.value); scanCode.value=''; evidencePhoto.value=''; const variance=result.line.variance_type; variance==='NONE'?message.success(`已确认 ${result.asset.asset_no}`):message.warning(`${result.asset.asset_no} 已记录差异：${variance}`); }finally{scanLoading.value=false;} }
async function approveLine(line:FixedAssetCountLine,status:'APPROVED'|'REJECTED'){ if(!countTaskId.value) return; await approveFixedAssetCountLineApi(countTaskId.value,line.id,{status,evidence_photo:line.evidence_photo,evidence_note:line.evidence_note}); countTask.value=await getFixedAssetCountApi(countTaskId.value); message.success(status==='APPROVED'?'差异已审批通过':'差异已驳回'); }
async function postCount(){ if(!countTaskId.value) return; countTask.value=await postFixedAssetCountApi(countTaskId.value); message.success('盘点差异已过账'); await loadCountTask(); }
function handleOnline(){ online.value=true; void syncOfflineScans(); }
function handleOffline(){ online.value=false; }
onMounted(async()=>{ online.value=navigator.onLine; periods.value=await getFinancePeriodsApi(); periodId.value=periods.value[0]?.id; plans.value=await getPaymentPlansApi(); statements.value=await getBankStatementsApi(); assets.value=await getFixedAssetsApi(); updateOfflinePending(); window.addEventListener('online',handleOnline); window.addEventListener('offline',handleOffline); if(periodId.value){ forecast.value=await rebuildCashFlowForecastApi(periodId.value); budgets.value=await getBudgetsApi(periodId.value); alerts.value=await getBudgetAlertsApi(periodId.value); } await refresh(); await syncOfflineScans(); });
onUnmounted(()=>{ window.removeEventListener('online',handleOnline); window.removeEventListener('offline',handleOffline); });
const columns=[{title:'物料',dataIndex:'material_code_snapshot'},{title:'名称',dataIndex:'material_name_snapshot'},{title:'期初数量',dataIndex:'opening_quantity',customRender:({text}:any)=>fmt(text)},{title:'收货数量',dataIndex:'receipt_quantity',customRender:({text}:any)=>fmt(text)},{title:'发出数量',dataIndex:'issue_quantity',customRender:({text}:any)=>fmt(text)},{title:'期末数量',dataIndex:'closing_quantity',customRender:({text}:any)=>fmt(text)},{title:'期末金额',dataIndex:'closing_value',customRender:({text}:any)=>fmt(text)},{title:'覆盖率',dataIndex:'coverage_rate',customRender:({text}:any)=>`${fmt(text)}%`}];
const planColumns=[{title:'计划号',dataIndex:'plan_no'},{title:'方向',dataIndex:'direction'},{title:'往来方',dataIndex:'partner_name_snapshot'},{title:'到期日',dataIndex:'due_date'},{title:'计划金额',dataIndex:'planned_amount',customRender:({text}:any)=>fmt(text)},{title:'已结算',dataIndex:'settled_amount',customRender:({text}:any)=>fmt(text)},{title:'状态',dataIndex:'status'}];
const bankColumns=[{title:'流水号',dataIndex:'statement_no'},{title:'日期',dataIndex:'transaction_date'},{title:'方向',dataIndex:'direction'},{title:'金额',dataIndex:'amount',customRender:({text}:any)=>fmt(text)},{title:'参考号',dataIndex:'reference_no'},{title:'状态',dataIndex:'status'},{title:'操作',key:'action',customRender:({record}:any)=>record.status!=='MATCHED'?h('a-button',{type:'link',onClick:()=>reconcile(record.id)},'自动对账'):h('span',{},'已完成')}];
const budgetColumns=[{title:'预算编号',dataIndex:'budget_no'},{title:'预算名称',dataIndex:'budget_name'},{title:'总额',dataIndex:'total_amount',customRender:({text}:any)=>fmt(text)},{title:'状态',dataIndex:'status'},{title:'操作',key:'action',customRender:({record}:any)=>record.status==='DRAFT'?h('a-button',{type:'link',onClick:()=>approveBudget(record.id)},'审批'):h('span',{},'已审批')}];
const alertColumns=[{title:'类型',dataIndex:'alert_type'},{title:'预算额',dataIndex:'budget_amount',customRender:({text}:any)=>fmt(text)},{title:'已执行',dataIndex:'consumed_amount',customRender:({text}:any)=>fmt(text)},{title:'执行率',dataIndex:'utilization_rate',customRender:({text}:any)=>`${fmt(text)}%`},{title:'说明',dataIndex:'detail'}];
const assetColumns=[{title:'资产编号',dataIndex:'asset_no'},{title:'资产名称',dataIndex:'asset_name'},{title:'类别',dataIndex:'category'},{title:'原值',dataIndex:'original_value',customRender:({text}:any)=>fmt(text)},{title:'累计折旧',dataIndex:'accumulated_depreciation',customRender:({text}:any)=>fmt(text)},{title:'净值',dataIndex:'net_value',customRender:({text}:any)=>fmt(text)},{title:'状态',dataIndex:'status'}];
const countLineColumns:any=[{title:'资产',dataIndex:'asset_id'},{title:'条码',dataIndex:'barcode_snapshot'},{title:'序列号',dataIndex:'serial_snapshot'},{title:'已盘',dataIndex:'counted',customRender:({text}:any)=>text?'是':'否'},{title:'差异',dataIndex:'variance_type'},{title:'审批',dataIndex:'approval_status'},{title:'操作',key:'action',customRender:({record}:any)=>record.variance_type!=='NONE'&&record.approval_status!=='APPROVED'?h('span',{},[h('a-button',{type:'link',onClick:()=>approveLine(record,'APPROVED')},'通过'),h('a-button',{type:'link',danger:true,onClick:()=>approveLine(record,'REJECTED')},'驳回')]):h('span',{},record.variance_type==='NONE'?'无需审批':record.approval_status)}];
</script>
<template>
  <Page title="库存计价与经营利润驾驶舱">
    <Space wrap style="margin-bottom:16px"><Select v-model:value="periodId" style="width:210px" placeholder="财务期间" :options="options" @change="refresh"/><a-button type="primary" :loading="loading" @click="calculate">运行库存计价</a-button><a-button @click="runDepreciation">计提财税双账折旧</a-button><a-button @click="closePeriod">月结检查/关账</a-button><a-button @click="syncTax">同步税务台账</a-button><a-button @click="rebuildCash">重建现金流预测</a-button><InputNumber v-model:value="shipmentId" :min="1" placeholder="发货单 ID"/><a-button @click="autoInvoice('AR')">销售自动开票</a-button><InputNumber v-model:value="receiptId" :min="1" placeholder="收货单 ID"/><a-button @click="autoInvoice('AP')">采购自动开票</a-button><a-button @click="assetFromReceipt">收货单转固定资产</a-button></Space>
    <Row :gutter="16"><Col :span="6"><Card><Statistic title="库存价值" :value="fmt(dashboard?.inventory_value)" suffix="CNY" /></Card></Col><Col :span="6"><Card><Statistic title="应收余额" :value="fmt(dashboard?.accounts_receivable)" suffix="CNY" /><Tag v-if="dashboard?.overdue_receivable" color="red">逾期 {{ fmt(dashboard.overdue_receivable) }}</Tag></Card></Col><Col :span="6"><Card><Statistic title="应付余额" :value="fmt(dashboard?.accounts_payable)" suffix="CNY" /><Tag v-if="dashboard?.overdue_payable" color="orange">逾期 {{ fmt(dashboard.overdue_payable) }}</Tag></Card></Col><Col :span="6"><Card><Statistic title="毛利率" :value="fmt(dashboard?.gross_margin_rate)" suffix="%" /></Card></Col></Row>
    <Card title="利润与现金流" style="margin-top:16px"><Space wrap><span>收入：{{ fmt(dashboard?.revenue) }}</span><span>销货成本：{{ fmt(dashboard?.cogs) }}</span><span>毛利：{{ fmt(dashboard?.gross_profit) }}</span><span>收款：{{ fmt(dashboard?.cash_in) }}</span><span>付款：{{ fmt(dashboard?.cash_out) }}</span><span>凭证：{{ dashboard?.voucher_count || 0 }} 张</span></Space></Card>
    <Card title="现金流预测" style="margin-top:16px"><Space wrap><span>预计流入：{{ fmt(forecast?.inflow) }}</span><span>预计流出：{{ fmt(forecast?.outflow) }}</span><span>预计净额：{{ fmt(forecast?.net_cash_flow) }}</span><span>预测笔数：{{ forecast?.rows?.length || 0 }}</span></Space></Card>
    <Card title="预算执行" style="margin-top:16px"><Table row-key="id" :columns="budgetColumns" :data-source="budgets" :pagination="{pageSize:8}" /></Card>
    <Card title="预算预警" style="margin-top:16px"><Table row-key="id" :columns="alertColumns" :data-source="alerts" :pagination="{pageSize:8}" /></Card>
    <Card title="固定资产台账" style="margin-top:16px"><Table row-key="id" :columns="assetColumns" :data-source="assets" :pagination="{pageSize:8}" /></Card>
    <Card title="移动扫码盘点 / 实时差异确认" style="margin-top:16px">
      <Space wrap class="scan-toolbar"><a-button @click="createCountTask">按当前资产创建任务</a-button><Input v-model:value="countZoneCode" placeholder="分区编码（如 A-01）" /><InputNumber v-model:value="countAssignedUserId" :min="1" placeholder="盘点负责人 ID" /><InputNumber v-model:value="countTaskId" :min="1" placeholder="盘点任务 ID" /><a-button @click="loadCountTask">加载任务</a-button><Input v-model:value="scanCode" allow-clear autofocus placeholder="扫描条码或序列号后回车" @press-enter="scanCount" /><InputNumber v-model:value="observedCostCenterId" :min="1" placeholder="实际成本中心 ID（可选）" /><label class="evidence-upload">拍照取证<input type="file" accept="image/*" capture="environment" @change="captureEvidence" /></label><Tag v-if="evidencePhoto" color="green">已附证据</Tag><a-button type="primary" :loading="scanLoading" @click="scanCount">确认扫码</a-button><a-button :disabled="!countTask || countTask.status !== 'COUNTING'" @click="postCount">差异过账</a-button></Space>
      <div class="scan-summary"><Tag :color="online ? 'green' : 'orange'">{{ online ? '在线' : '离线' }}</Tag><Tag v-if="offlinePending" color="orange">待同步 {{ offlinePending }}</Tag><a-button v-if="offlinePending" size="small" :loading="syncingOffline" @click="syncOfflineScans">立即同步</a-button><template v-if="countTask"><Tag color="blue">{{ countTask.task_no }}</Tag><Tag v-if="countTask.zone_code" color="purple">分区 {{ countTask.zone_code }}</Tag><Tag :color="countTask.status === 'COUNTING' ? 'green' : 'default'">{{ countTask.status }}</Tag><span>已扫描 {{ countTask.lines.filter((line)=>line.counted).length }} / {{ countTask.lines.length }} 项</span><span v-if="lastScan">最近：{{ lastScan.asset_no }} · {{ lastScan.asset_name }}</span></template></div>
      <Table v-if="countTask" row-key="id" :data-source="countTask.lines" :pagination="{pageSize:6}" :columns="countLineColumns" />
      <div v-else class="scan-empty">加载盘点任务后即可在手机或 PDA 上连续扫码，扫码结果会即时回写并显示账实差异。</div>
    </Card>
    <Card title="库存计价结果" style="margin-top:16px"><Table row-key="id" :loading="loading" :columns="columns" :data-source="valuation" :pagination="{pageSize:10}" /></Card>
    <Card title="收付款计划" style="margin-top:16px"><Table row-key="id" :columns="planColumns" :data-source="plans" :pagination="{pageSize:10}" /></Card>
    <Card title="银行流水对账" style="margin-top:16px"><Table row-key="id" :columns="bankColumns" :data-source="statements" :pagination="{pageSize:10}" /></Card>
  </Page>
</template>
<style scoped>
.scan-toolbar { width: 100%; }
.scan-toolbar :deep(.ant-input) { min-width: 260px; }
.scan-summary { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin: 12px 0; }
.scan-empty { color: #8c8c8c; padding: 16px 0; }
.evidence-upload { display: inline-flex; align-items: center; gap: 6px; cursor: pointer; padding: 4px 10px; border: 1px dashed #bfbfbf; border-radius: 4px; }
.evidence-upload input { display: none; }
@media (max-width: 768px) {
  .scan-toolbar { display: flex; flex-direction: column; align-items: stretch; }
  .scan-toolbar > * { width: 100%; }
  .scan-toolbar :deep(.ant-input), .scan-toolbar :deep(.ant-input-number) { min-width: 100%; width: 100%; }
}
</style>
